{
  "schema_version": "1.4.0",
  "id": "GHSA-vgrw-7cvw-pwgx",
  "modified": "2025-03-31T15:30:49Z",
  "published": "2025-03-31T15:30:48Z",
  "aliases": [
    "CVE-2025-2999"
  ],
  "details": "A vulnerability was found in PyTorch 2.6.0. It has been rated as critical. Affected by this issue is the function torch.nn.utils.rnn.unpack_sequence. The manipulation leads to memory corruption. Attacking locally is a requirement. The exploit has been disclosed to the public and may be used.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:L/I:L/A:L"
    },
    {
      "type": "CVSS_V4",
      "score": "CVSS:4.0/AV:L/AC:L/AT:N/PR:L/UI:N/VC:L/VI:L/VA:L/SC:N/SI:N/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X"
    }
  ],
  "affected": [],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2025-2999"
    },
    {
      "type": "WEB",
      "url": "https://github.com/pytorch/pytorch/issues/149622"
    },
    {
      "type": "WEB",
      "url": "https://github.com/pytorch/pytorch/issues/149622#issue-2935495265"
    },
    {
      "type": "WEB",
      "url": "https://vuldb.com/?ctiid.302048"
    },
    {
      "type": "WEB",
      "url": "https://vuldb.com/?id.302048"
    },
    {
      "type": "WEB",
      "url": "https://vuldb.com/?submit.524198"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-119"
    ],
    "severity": "MODERATE",
    "github_reviewed": false,
    "github_reviewed_at": null,
    "nvd_published_at": "2025-03-31T15:15:44Z"
  }
}