{
  "schema_version": "1.4.0",
  "id": "GHSA-qm85-96h4-7f94",
  "modified": "2025-07-11T15:31:36Z",
  "published": "2025-07-11T15:31:36Z",
  "aliases": [
    "CVE-2025-53862"
  ],
  "details": "A flaw was found in Ansible. Three API endpoints are accessible and return verbose, unauthenticated responses. This flaw allows a malicious user to access data that may contain important information.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:A/AC:L/PR:L/UI:N/S:U/C:L/I:N/A:N"
    }
  ],
  "affected": [],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2025-53862"
    },
    {
      "type": "WEB",
      "url": "https://access.redhat.com/security/cve/CVE-2025-53862"
    },
    {
      "type": "WEB",
      "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2379359"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-497"
    ],
    "severity": "LOW",
    "github_reviewed": false,
    "github_reviewed_at": null,
    "nvd_published_at": "2025-07-11T13:15:59Z"
  }
}